### ISSUE TITLE
Create a Github Page

### ISSUE THREAD

**Issue by yelled3** [sidekiq-orm/sidekiq-activerecord#12]
most of the content is already ready in the wiki.

@seuros /cc

**Comment by yelled3** [comment]
added placeholder:
http://sidekiq-orm.github.io/

**Comment by seuros** [comment]
:+1:

**Comment by yelled3** [comment]
@seuros updated -  WDYT?

**Comment by yelled3** [comment]
@seuros closing - reopen if you have any feedback
