### ISSUE TITLE
Config Travis CI

### ISSUE THREAD

**Issue by yelled3** [sidekiq-orm/sidekiq-activerecord#6]
@seuros wanna take this one?

**Comment by seuros** [comment]
Yes

**Comment by yelled3** [comment]
thanks :-)

**Comment by yelled3** [comment]
@seuros  there's some issue with byebug:

```
Gem::InstallError: byebug requires Ruby version >= 2.0.0.
An error occurred while installing byebug (3.1.2), and Bundler cannot continue.
Make sure that `gem install byebug -v '3.1.2'` succeeds before bundling.
```

https://travis-ci.org/sidekiq-orm/sidekiq-activerecord/jobs/26560838

**Comment by seuros** [comment]
yes, i noticed that. byebug requires ruby 2+. 
I will fix that in few hours from now (just have to push the changes).

**Comment by yelled3** [comment]
@seuros thanks man - appreciated.
